### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by philipcunningham** [foxnewsnetwork/arrows#1]
I'd really like to contribute to the project but not sure where to begin. I authored another gem to add `Maybe` to the Ruby ecosystem and focussed on writing tests to prove it adhered to various laws, e.g. https://github.com/filib/ribimaybe/blob/master/spec/applicative_functor_spec.rb. Is this something you feel would be a valuable addition to the to `arrows`?

**Comment by foxnewsnetwork** [comment]
YES! That's be great! I wrote this library because I was really butt-hurt about writing cancerous unrefactorable monadic code in my rails e-commerce websites, so I haven't had any time to actually make sure this library obeys the appropriate laws. But if you could do it, you are awesome. 

Also, it's good to see Haskell's influence more and more creep into Ruby.

**Comment by philipcunningham** [comment]
Nice one! I'll fork and have a bash.
